version: '2'

services:
  server:
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      CCC: "internal-lb.${BNR_ENVIRONMENT}.bionano.bio:9000"
    logging:
      driver: json-file
    links:
      - redis

  redis:
    restart: always
    ports:
      #Don't expose this port to the host, only linked containers.
      - "6379"
    volumes:
      - ./server/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      # This is the where the db will be writting. It is defined in ./server/etc/redis/redis.conf
      - redis-data:/data