version: '2'

services:
  server:
    image: "quay.io/bionano/mdtapps_server:${VERSION}"
    environment:
      CCC: "internal-lb.${BNR_ENVIRONMENT}.bionano.bio:9000"
      REDIS_HOST: "redis.${BNR_ENVIRONMENT}.bionano.bio"
      #share sql postgress cluster with gctor
      PGHOST: "gctor-db${BNR_ENV_URL_SUFFIX}.bionano.bio"
      PGPASSWORD:
      PGDATABASE:
      NODE_ENV: "production"
      FRONTEND_URL: "http://molsim${BNR_ENV_URL_SUFFIX}.lifesciences.autodesk.com"
      URL: "http://molsim${BNR_ENV_URL_SUFFIX}.lifesciences.autodesk.com"
      REDIS_HOST: "redis-mst.${BNR_ENVIRONMENT}.bionano.bio"
      FLUENT_PORT: '24226'
    extra_hosts:
      - "fluentd:172.17.0.1"
    logging:
      driver: json-file
      options:
        max-size: 50m
