version: '2'

services:

  client:
    build: "client/."
    image: "cloud-workflow-client:latest"
    command: ["npm", "run", "dev"]
    ports:
      - "4000:4000"
    links:
      - workflows

  workflows:
    build: "server/."
    image: "cloud-workflow-server:latest"
    command: ["forever", "build/server/server-workflow.js"]
    volumes:
      - ./server/test/examples:/app/test/examples
