version: '2'

services:

  client:
    # restart: always
    build:
      context: .
    # command: ["npm", "run", "dev"]
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      # HOST_PWD: "${PWD}"
    # links:
    #   - workflow-server


  # server:
  #   restart: always
  #   build:
  #     context: .
  #   command: ["nodemon", "/app/server/build/server/server-workflow.js"]
  #   ports:
  #     - "9000:4040"
  #   environment:
  #     PORT: "4040"
  #     HOST_PWD: "${PWD}"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - "${PWD}/tmp:/app/tmp"
  #     - "${PWD}/gitcache:/app/gitcache"
  #     # - ./tmp:/app/server/tmp
  #     #Uncomment this if you are doing workflow development
  #     # - ./client/workflow_convert_pdb:/app/client/workflow_convert_pdb
  #     #Uncomment this if you are doing client development
  #     # - ./client/dist:/app/client/dist
  #     # Uncomment this if you are doing server development
  #     # - ./server/lib/workflow-execution-server/build/server:/app/server/build/server


  # workflow-server:
  #   restart: always
  #   image: quay.io/bionano/workflow-execution-server:b5e22842
  #   command: ["nodemon", "--watch", "/app/", "/app/server/server-workflow.js"]
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - "${PWD}/tmp:/app/tmp"
  #     - "${PWD}/gitcache:/app/gitcache"
  #     - "./build/client/dist:/app/client/dist"
  #     - "./client/workflow_convert_pdb:/app/client/workflow_convert_pdb"
  #   ports:
  #     - "9000:4040"
  #   environment:
  #     HOST_PWD: "${PWD}"
  #     PORT: "4040"