version: '2'

services:
  client:
    image: "quay.io/bionano/molecular-design-apps:${VERSION}"
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      WORKFLOW_SERVER_ADDRESS: "internal-lb.${BNR_ENVIRONMENT}.bionano.bio:9000"
    logging:
      driver: json-file
