version: '2'

services:

  server:
    build:
      context: .
    command: ["nodemon", "/app/server/lib/workflow-execution-server/build/server/server-workflow.js"]
    ports:
      - "4000:4000"
    environment:
      HOST_PWD: "${PWD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp:/app/server/tmp
      #Uncomment this if you are doing workflow development
      #- ./client/workflow_convert_pdb:/app/client/workflow_convert_pdb
      #Uncomment this if you are doing client development
      #- ./client/dist:/app/client/dist
      #Uncomment this if you are doing server development
      #- ./server/lib/workflow-execution-server/build/server:/app/server/lib/workflow-execution-server/build/server
