version: '2'


volumes:
  redis-data:
    driver: local

services:
  server:
    build:
      context: .
    links:
      - redis

  redis:
    restart: always
    volumes:
      - ./server/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      # This is the where the db will be writting. It is defined in ./server/etc/redis/redis.conf
      - redis-data:/data
