version: '2'


volumes:
  redis-data:
    driver: local

services:

  server:
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
    links:
      - redis

  redis:
    restart: always
    image: redis:3.2.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      #Don't expose this port to the host, only linked containers.
      # - "6379"
      - "6379:6379"
    volumes:
      - ./server/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      # This is the where the db will be writting. It is defined in ./server/etc/redis/redis.conf
      - redis-data:/data
