version: '2'

volumes:
  redis-data:
    driver: local

services:
  server:
    image: "quay.io/bionano/mdtapps_server:${VERSION}"
    environment:
      CCC: "ccc.bionano.autodesk.com:9000"
      NODE_ENV: "production"
      FRONTEND_URL: "http://molsim.bionano.autodesk.com"
      URL: "http://molsim.bionano.autodesk.com"
      REDIS_HOST: "redis.${BNR_ENVIRONMENT}.bionano.bio"
    logging:
      driver: json-file
      options:
        max-size: 50m
