version: '2'

volumes:
  redis-data:
    driver: local

services:
  server:
    image: "quay.io/bionano/mdtapps_server:${VERSION}"
    environment:
      CCC: "ccc.bionano.autodesk.com:9000"
      NODE_ENV: "production"
      FRONTEND_URL: "http://molsim.bionano.autodesk.com/"
    logging:
      driver: json-file
      options:
        max-size: 50m
    links:
      - redis

  redis:
    restart: always
    ports:
      #Don't expose this port to the host, only linked containers.
      - "6379"
    volumes:
      - ./server/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      # This is the where the db will be writting. It is defined in ./server/etc/redis/redis.conf
      - redis-data:/data
    logging:
      driver: json-file
      options:
        max-size: 50m
